_upload:
    pattern:  /
    defaults: { _controller: FreshBooksPicrBundle:Upload:index }

_ajax_upload:
    pattern:  /upload
    defaults: { _controller: FreshBooksPicrBundle:Upload:ajaxUpload }

_show:
    pattern:  /i/{image}
    defaults: { _controller: FreshBooksPicrBundle:Upload:show }

_about:
    pattern:  /about
    defaults: { _controller: FreshBooksPicrBundle:About:index }

_recent:
    pattern:  /recent
    defaults: { _controller: FreshBooksPicrBundle:Recent:index }
